### ISSUE TITLE
tags are removed before being refreshed on load

### ISSUE THREAD

**Issue by danielroe** [vueuse/head#52] opened 2022-02-09 14:56 UTC
This line removes all link tags that aren't controlled by vueuse/head: https://github.com/vueuse/head/blob/392e8c8ca91df27d9b067dad8c2d9886b53ac756/src/index.ts#L208

If I remove that then this section does the same thing when run by vite-ssg because `querySelector('link[key="null"]')` just returns the first `<link>` due to a jsdom bug:
https://github.com/vueuse/head/blob/392e8c8ca91df27d9b067dad8c2d9886b53ac756/src/index.ts#L213-L218

_Originally posted by @KaelWD in https://github.com/vueuse/head/issues/45#issuecomment-996908307_

**Comment by danielroe** [comment] 2022-02-13 01:11
in fact I think this may be a downstream issue: https://github.com/nuxt/framework/pull/3212

**Comment by KaelWD** [comment] 2022-02-13 03:39
My original comment was in the vuetify docs with just vite-ssg.

**Comment by harlan-zw** [comment] 2022-09-19 05:24
Related https://github.com/vueuse/head/issues/75

**Comment by harlan-zw** [comment] 2022-09-19 05:35
Seems like this may be fixed given the above comment, otherwise it's a duplicate of #75.

Feel free to re-open if that's not the case.

**Closed by harlan-zw** 2022-09-19 05:35 UTC
Labels: bug
